name: Create Archive
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "giquon"
        git config --global user.email "d.janssen00@gmail.com"
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force